### ISSUE TITLE
Hotspot, Differentiate between A/P/S and D/H

### ISSUE THREAD

**Issue by Buster14** [pilotak/homeassistant-mikrotik-api#1]
Hi, i'm trying to differentiate HA trigger between A, P, S and D / H status in Hotspot > Hosts status.
The reason for this is that there's some clients that only connects and not logged in to my hotspot server, and that messes up the automation. My AP is unifi and my radius server and hotspot server is mikrotik. Currently using unifi counter as trigger but of course i'm getting alot of false positive trigger due to above issue

Can this be done with this integration?
How would i create a sensor then?

**Comment by pilotak** [comment]
Hi,
currently there is no way to expose things read to the sensor

**Comment by Buster14** [comment]
Not even with official mikrotik integration? 
Is this because nobody developed it yet, or simply not possible due to their API?

**Comment by pilotak** [comment]
Official integration in only for presence detection, my is basic API. If something more advanced is required i write the script in mikrotik and only calling the API to run the file. Having a sensor based on API output is of course possible, but you would need to write your own intergration.

Maybe you can try the luck with https://github.com/tomaae/homeassistant-mikrotik_router
